// AUTOGENERATED by generator/codegen.py -- do not edit
#include "qt6_runtime.hpp"
#include <QtCore/QtCore>

static qt6rb::ClassInfo cls_QObject = { "QObject", Qnil, [](void* p) { delete static_cast<QObject*>(p); } };
static qt6rb::ClassInfo cls_QTimer = { "QTimer", Qnil, [](void* p) { delete static_cast<QTimer*>(p); } };

static VALUE rb_QObject_s_new(int argc, VALUE* argv, VALUE self) {
  if (argc == 0) {
    return qt6rb::wrap_qobject(new QObject(), &cls_QObject);
  }
  if (argc == 1) {
    return qt6rb::wrap_qobject(new QObject(static_cast<QObject*>(qt6rb::unwrap(argv[0], &cls_QObject))), &cls_QObject);
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#new (%d)", argc);
}

static VALUE rb_QObject_object_name(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 0) {
    return qt6rb::from_qstring(o->objectName());
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#object_name (%d)", argc);
}

static VALUE rb_QObject_is_widget_type(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 0) {
    return (o->isWidgetType()) ? Qtrue : Qfalse;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#is_widget_type (%d)", argc);
}

static VALUE rb_QObject_is_window_type(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 0) {
    return (o->isWindowType()) ? Qtrue : Qfalse;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#is_window_type (%d)", argc);
}

static VALUE rb_QObject_is_quick_item_type(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 0) {
    return (o->isQuickItemType()) ? Qtrue : Qfalse;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#is_quick_item_type (%d)", argc);
}

static VALUE rb_QObject_is_qml_exposed(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 0) {
    return (o->isQmlExposed()) ? Qtrue : Qfalse;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#is_qml_exposed (%d)", argc);
}

static VALUE rb_QObject_signals_blocked(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 0) {
    return (o->signalsBlocked()) ? Qtrue : Qfalse;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#signals_blocked (%d)", argc);
}

static VALUE rb_QObject_block_signals(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 1) {
    return (o->blockSignals(RTEST(argv[0]))) ? Qtrue : Qfalse;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#block_signals (%d)", argc);
}

static VALUE rb_QObject_start_timer(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 1) {
    return INT2NUM(o->startTimer(NUM2INT(argv[0])));
  }
  if (argc == 2) {
    return INT2NUM(o->startTimer(NUM2INT(argv[0]), static_cast<Qt::TimerType>(NUM2INT(argv[1]))));
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#start_timer (%d)", argc);
}

static VALUE rb_QObject_kill_timer(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 1) {
    o->killTimer(NUM2INT(argv[0]));
    return Qnil;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#kill_timer (%d)", argc);
}

static VALUE rb_QObject_set_parent(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 1) {
    o->setParent(static_cast<QObject*>(qt6rb::unwrap(argv[0], &cls_QObject)));
    return Qnil;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#set_parent (%d)", argc);
}

static VALUE rb_QObject_install_event_filter(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 1) {
    o->installEventFilter(static_cast<QObject*>(qt6rb::unwrap(argv[0], &cls_QObject)));
    return Qnil;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#install_event_filter (%d)", argc);
}

static VALUE rb_QObject_remove_event_filter(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 1) {
    o->removeEventFilter(static_cast<QObject*>(qt6rb::unwrap(argv[0], &cls_QObject)));
    return Qnil;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#remove_event_filter (%d)", argc);
}

static VALUE rb_QObject_disconnect(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 0) {
    return (o->disconnect()) ? Qtrue : Qfalse;
  }
  if (argc == 1) {
    return (o->disconnect(StringValueCStr(argv[0]))) ? Qtrue : Qfalse;
  }
  if (argc == 2) {
    return (o->disconnect(StringValueCStr(argv[0]), static_cast<QObject*>(qt6rb::unwrap(argv[1], &cls_QObject)))) ? Qtrue : Qfalse;
  }
  if (argc == 3) {
    return (o->disconnect(StringValueCStr(argv[0]), static_cast<QObject*>(qt6rb::unwrap(argv[1], &cls_QObject)), StringValueCStr(argv[2]))) ? Qtrue : Qfalse;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#disconnect (%d)", argc);
}

static VALUE rb_QObject_dump_object_tree(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 0) {
    o->dumpObjectTree();
    return Qnil;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#dump_object_tree (%d)", argc);
}

static VALUE rb_QObject_dump_object_info(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 0) {
    o->dumpObjectInfo();
    return Qnil;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#dump_object_info (%d)", argc);
}

static VALUE rb_QObject_parent(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 0) {
    return qt6rb::wrap_qobject((o->parent()), &cls_QObject);
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#parent (%d)", argc);
}

static VALUE rb_QObject_inherits(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 1) {
    return (o->inherits(StringValueCStr(argv[0]))) ? Qtrue : Qfalse;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#inherits (%d)", argc);
}

static VALUE rb_QObject_delete_later(int argc, VALUE* argv, VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  if (argc == 0) {
    o->deleteLater();
    return Qnil;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#delete_later (%d)", argc);
}

static VALUE rb_QObject_s_tr(int argc, VALUE* argv, VALUE self) {
  if (argc == 3) {
    return qt6rb::from_qstring(QObject::tr(StringValueCStr(argv[0]), StringValueCStr(argv[1]), NUM2INT(argv[2])));
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#tr (%d)", argc);
}

static VALUE rb_QObject_s_disconnect(int argc, VALUE* argv, VALUE self) {
  if (argc == 4) {
    return (QObject::disconnect(static_cast<QObject*>(qt6rb::unwrap(argv[0], &cls_QObject)), StringValueCStr(argv[1]), static_cast<QObject*>(qt6rb::unwrap(argv[2], &cls_QObject)), StringValueCStr(argv[3]))) ? Qtrue : Qfalse;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QObject#disconnect (%d)", argc);
}

static VALUE rb_QObject_on_destroyed(VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  VALUE proc = rb_block_proc();
  qt6rb::retain_proc(proc);
  QObject::connect(o, &QObject::destroyed, o, [proc](QObject* a0) {
    VALUE args[] = { qt6rb::wrap_qobject((a0), &cls_QObject) };
    qt6rb::call_proc(proc, 1, args);
  });
  return self;
}

static VALUE rb_QObject_on_object_name_changed(VALUE self) {
  QObject* o = static_cast<QObject*>(qt6rb::unwrap(self, &cls_QObject));
  VALUE proc = rb_block_proc();
  qt6rb::retain_proc(proc);
  QObject::connect(o, &QObject::objectNameChanged, o, [proc](QString a0) {
    VALUE args[] = { qt6rb::from_qstring(a0) };
    qt6rb::call_proc(proc, 1, args);
  });
  return self;
}

static VALUE rb_QTimer_s_new(int argc, VALUE* argv, VALUE self) {
  if (argc == 0) {
    return qt6rb::wrap_qobject(new QTimer(), &cls_QTimer);
  }
  if (argc == 1) {
    return qt6rb::wrap_qobject(new QTimer(static_cast<QObject*>(qt6rb::unwrap(argv[0], &cls_QObject))), &cls_QTimer);
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QTimer#new (%d)", argc);
}

static VALUE rb_QTimer_is_active(int argc, VALUE* argv, VALUE self) {
  QTimer* o = static_cast<QTimer*>(qt6rb::unwrap(self, &cls_QTimer));
  if (argc == 0) {
    return (o->isActive()) ? Qtrue : Qfalse;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QTimer#is_active (%d)", argc);
}

static VALUE rb_QTimer_timer_id(int argc, VALUE* argv, VALUE self) {
  QTimer* o = static_cast<QTimer*>(qt6rb::unwrap(self, &cls_QTimer));
  if (argc == 0) {
    return INT2NUM(o->timerId());
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QTimer#timer_id (%d)", argc);
}

static VALUE rb_QTimer_id(int argc, VALUE* argv, VALUE self) {
  QTimer* o = static_cast<QTimer*>(qt6rb::unwrap(self, &cls_QTimer));
  if (argc == 0) {
    return INT2NUM(static_cast<int>(o->id()));
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QTimer#id (%d)", argc);
}

static VALUE rb_QTimer_set_interval(int argc, VALUE* argv, VALUE self) {
  QTimer* o = static_cast<QTimer*>(qt6rb::unwrap(self, &cls_QTimer));
  if (argc == 1) {
    o->setInterval(NUM2INT(argv[0]));
    return Qnil;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QTimer#set_interval (%d)", argc);
}

static VALUE rb_QTimer_interval(int argc, VALUE* argv, VALUE self) {
  QTimer* o = static_cast<QTimer*>(qt6rb::unwrap(self, &cls_QTimer));
  if (argc == 0) {
    return INT2NUM(o->interval());
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QTimer#interval (%d)", argc);
}

static VALUE rb_QTimer_remaining_time(int argc, VALUE* argv, VALUE self) {
  QTimer* o = static_cast<QTimer*>(qt6rb::unwrap(self, &cls_QTimer));
  if (argc == 0) {
    return INT2NUM(o->remainingTime());
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QTimer#remaining_time (%d)", argc);
}

static VALUE rb_QTimer_set_timer_type(int argc, VALUE* argv, VALUE self) {
  QTimer* o = static_cast<QTimer*>(qt6rb::unwrap(self, &cls_QTimer));
  if (argc == 1) {
    o->setTimerType(static_cast<Qt::TimerType>(NUM2INT(argv[0])));
    return Qnil;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QTimer#set_timer_type (%d)", argc);
}

static VALUE rb_QTimer_timer_type(int argc, VALUE* argv, VALUE self) {
  QTimer* o = static_cast<QTimer*>(qt6rb::unwrap(self, &cls_QTimer));
  if (argc == 0) {
    return INT2NUM(static_cast<int>(o->timerType()));
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QTimer#timer_type (%d)", argc);
}

static VALUE rb_QTimer_set_single_shot(int argc, VALUE* argv, VALUE self) {
  QTimer* o = static_cast<QTimer*>(qt6rb::unwrap(self, &cls_QTimer));
  if (argc == 1) {
    o->setSingleShot(RTEST(argv[0]));
    return Qnil;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QTimer#set_single_shot (%d)", argc);
}

static VALUE rb_QTimer_is_single_shot(int argc, VALUE* argv, VALUE self) {
  QTimer* o = static_cast<QTimer*>(qt6rb::unwrap(self, &cls_QTimer));
  if (argc == 0) {
    return (o->isSingleShot()) ? Qtrue : Qfalse;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QTimer#is_single_shot (%d)", argc);
}

static VALUE rb_QTimer_start(int argc, VALUE* argv, VALUE self) {
  QTimer* o = static_cast<QTimer*>(qt6rb::unwrap(self, &cls_QTimer));
  if (argc == 1) {
    o->start(NUM2INT(argv[0]));
    return Qnil;
  }
  if (argc == 0) {
    o->start();
    return Qnil;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QTimer#start (%d)", argc);
}

static VALUE rb_QTimer_stop(int argc, VALUE* argv, VALUE self) {
  QTimer* o = static_cast<QTimer*>(qt6rb::unwrap(self, &cls_QTimer));
  if (argc == 0) {
    o->stop();
    return Qnil;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QTimer#stop (%d)", argc);
}

static VALUE rb_QTimer_s_tr(int argc, VALUE* argv, VALUE self) {
  if (argc == 3) {
    return qt6rb::from_qstring(QTimer::tr(StringValueCStr(argv[0]), StringValueCStr(argv[1]), NUM2INT(argv[2])));
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QTimer#tr (%d)", argc);
}

static VALUE rb_QTimer_s_single_shot(int argc, VALUE* argv, VALUE self) {
  if (argc == 3) {
    QTimer::singleShot(NUM2INT(argv[0]), static_cast<QObject*>(qt6rb::unwrap(argv[1], &cls_QObject)), StringValueCStr(argv[2]));
    return Qnil;
  }
  if (argc == 4) {
    QTimer::singleShot(NUM2INT(argv[0]), static_cast<Qt::TimerType>(NUM2INT(argv[1])), static_cast<QObject*>(qt6rb::unwrap(argv[2], &cls_QObject)), StringValueCStr(argv[3]));
    return Qnil;
  }
  rb_raise(rb_eArgError, "wrong number of arguments for QTimer#single_shot (%d)", argc);
}

static VALUE rb_QTimer_on_timeout(VALUE self) {
  QTimer* o = static_cast<QTimer*>(qt6rb::unwrap(self, &cls_QTimer));
  VALUE proc = rb_block_proc();
  qt6rb::retain_proc(proc);
  QObject::connect(o, &QTimer::timeout, o, [proc]() {
    qt6rb::call_proc(proc, 0, nullptr);
  });
  return self;
}

extern "C" void Init_qt6() {
  VALUE mQt = qt6rb::module_qt();
  qt6rb::init_core(mQt);
  qt6rb::define_class(&cls_QObject, "Object", Qnil);
  rb_undef_alloc_func(cls_QObject.rb_class);
  qt6rb::define_class(&cls_QTimer, "Timer", cls_QObject.rb_class);
  rb_undef_alloc_func(cls_QTimer.rb_class);
  rb_define_singleton_method(cls_QObject.rb_class, "new", RUBY_METHOD_FUNC(rb_QObject_s_new), -1);
  rb_define_method(cls_QObject.rb_class, "object_name", RUBY_METHOD_FUNC(rb_QObject_object_name), -1);
  rb_define_method(cls_QObject.rb_class, "is_widget_type", RUBY_METHOD_FUNC(rb_QObject_is_widget_type), -1);
  rb_define_method(cls_QObject.rb_class, "is_window_type", RUBY_METHOD_FUNC(rb_QObject_is_window_type), -1);
  rb_define_method(cls_QObject.rb_class, "is_quick_item_type", RUBY_METHOD_FUNC(rb_QObject_is_quick_item_type), -1);
  rb_define_method(cls_QObject.rb_class, "is_qml_exposed", RUBY_METHOD_FUNC(rb_QObject_is_qml_exposed), -1);
  rb_define_method(cls_QObject.rb_class, "signals_blocked", RUBY_METHOD_FUNC(rb_QObject_signals_blocked), -1);
  rb_define_method(cls_QObject.rb_class, "block_signals", RUBY_METHOD_FUNC(rb_QObject_block_signals), -1);
  rb_define_method(cls_QObject.rb_class, "start_timer", RUBY_METHOD_FUNC(rb_QObject_start_timer), -1);
  rb_define_method(cls_QObject.rb_class, "kill_timer", RUBY_METHOD_FUNC(rb_QObject_kill_timer), -1);
  rb_define_method(cls_QObject.rb_class, "set_parent", RUBY_METHOD_FUNC(rb_QObject_set_parent), -1);
  rb_define_alias(cls_QObject.rb_class, "parent=", "set_parent");
  rb_define_method(cls_QObject.rb_class, "install_event_filter", RUBY_METHOD_FUNC(rb_QObject_install_event_filter), -1);
  rb_define_method(cls_QObject.rb_class, "remove_event_filter", RUBY_METHOD_FUNC(rb_QObject_remove_event_filter), -1);
  rb_define_method(cls_QObject.rb_class, "disconnect", RUBY_METHOD_FUNC(rb_QObject_disconnect), -1);
  rb_define_method(cls_QObject.rb_class, "dump_object_tree", RUBY_METHOD_FUNC(rb_QObject_dump_object_tree), -1);
  rb_define_method(cls_QObject.rb_class, "dump_object_info", RUBY_METHOD_FUNC(rb_QObject_dump_object_info), -1);
  rb_define_method(cls_QObject.rb_class, "parent", RUBY_METHOD_FUNC(rb_QObject_parent), -1);
  rb_define_method(cls_QObject.rb_class, "inherits", RUBY_METHOD_FUNC(rb_QObject_inherits), -1);
  rb_define_method(cls_QObject.rb_class, "delete_later", RUBY_METHOD_FUNC(rb_QObject_delete_later), -1);
  rb_define_singleton_method(cls_QObject.rb_class, "tr", RUBY_METHOD_FUNC(rb_QObject_s_tr), -1);
  rb_define_singleton_method(cls_QObject.rb_class, "disconnect", RUBY_METHOD_FUNC(rb_QObject_s_disconnect), -1);
  rb_define_method(cls_QObject.rb_class, "on_destroyed", RUBY_METHOD_FUNC(rb_QObject_on_destroyed), 0);
  rb_define_method(cls_QObject.rb_class, "on_object_name_changed", RUBY_METHOD_FUNC(rb_QObject_on_object_name_changed), 0);
  rb_define_singleton_method(cls_QTimer.rb_class, "new", RUBY_METHOD_FUNC(rb_QTimer_s_new), -1);
  rb_define_method(cls_QTimer.rb_class, "is_active", RUBY_METHOD_FUNC(rb_QTimer_is_active), -1);
  rb_define_method(cls_QTimer.rb_class, "timer_id", RUBY_METHOD_FUNC(rb_QTimer_timer_id), -1);
  rb_define_method(cls_QTimer.rb_class, "id", RUBY_METHOD_FUNC(rb_QTimer_id), -1);
  rb_define_method(cls_QTimer.rb_class, "set_interval", RUBY_METHOD_FUNC(rb_QTimer_set_interval), -1);
  rb_define_alias(cls_QTimer.rb_class, "interval=", "set_interval");
  rb_define_method(cls_QTimer.rb_class, "interval", RUBY_METHOD_FUNC(rb_QTimer_interval), -1);
  rb_define_method(cls_QTimer.rb_class, "remaining_time", RUBY_METHOD_FUNC(rb_QTimer_remaining_time), -1);
  rb_define_method(cls_QTimer.rb_class, "set_timer_type", RUBY_METHOD_FUNC(rb_QTimer_set_timer_type), -1);
  rb_define_alias(cls_QTimer.rb_class, "timer_type=", "set_timer_type");
  rb_define_method(cls_QTimer.rb_class, "timer_type", RUBY_METHOD_FUNC(rb_QTimer_timer_type), -1);
  rb_define_method(cls_QTimer.rb_class, "set_single_shot", RUBY_METHOD_FUNC(rb_QTimer_set_single_shot), -1);
  rb_define_alias(cls_QTimer.rb_class, "single_shot=", "set_single_shot");
  rb_define_method(cls_QTimer.rb_class, "is_single_shot", RUBY_METHOD_FUNC(rb_QTimer_is_single_shot), -1);
  rb_define_method(cls_QTimer.rb_class, "start", RUBY_METHOD_FUNC(rb_QTimer_start), -1);
  rb_define_method(cls_QTimer.rb_class, "stop", RUBY_METHOD_FUNC(rb_QTimer_stop), -1);
  rb_define_singleton_method(cls_QTimer.rb_class, "tr", RUBY_METHOD_FUNC(rb_QTimer_s_tr), -1);
  rb_define_singleton_method(cls_QTimer.rb_class, "single_shot", RUBY_METHOD_FUNC(rb_QTimer_s_single_shot), -1);
  rb_define_method(cls_QTimer.rb_class, "on_timeout", RUBY_METHOD_FUNC(rb_QTimer_on_timeout), 0);
}
